// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Greeting = require("./greeting.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function app() {
  return ReasonReact.element(undefined, undefined, Greeting.make(/* array */[]));
}

exports.app = app;
/* Greeting Not a pure module */
