// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var TextInput$BsReactNative = require("bs-react-native/lib/js/src/components/textInput.js");

var component = ReasonReact.reducerComponent("Greeting");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(1),
                                        /* :: */[
                                          Style$BsReactNative.justifyContent(/* Center */2),
                                          /* :: */[
                                            Style$BsReactNative.alignItems(/* Center */2),
                                            /* [] */0
                                          ]
                                        ]
                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                Style$BsReactNative.fontWeight(/* Bold */737455525),
                                                /* [] */0
                                              ])), undefined, undefined, undefined, undefined, undefined, undefined, "Reason is great!", /* array */[])),
                              ReasonReact.element(undefined, undefined, TextInput$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.height(/* Pt */Block.__(0, [40])),
                                                  /* :: */[
                                                    Style$BsReactNative.width(/* Pt */Block.__(0, [200])),
                                                    /* :: */[
                                                      Style$BsReactNative.borderWidth(1),
                                                      /* :: */[
                                                        Style$BsReactNative.marginTop(/* Pt */Block.__(0, [40])),
                                                        /* :: */[
                                                          Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (text) {
                                            return Curry._1(self[/* send */3], /* Change */[text]);
                                          }), undefined, undefined, undefined, undefined, undefined, undefined, "Username", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[])),
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                Style$BsReactNative.marginTop(/* Pt */Block.__(0, [40])),
                                                /* :: */[
                                                  Style$BsReactNative.fontWeight(/* Bold */737455525),
                                                  /* [] */0
                                                ]
                                              ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Hello " + (self[/* state */1][/* name */0] + " !!!")]))
                            ]));
            }),
          /* initialState */(function () {
              return /* record */[/* name */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* name */action[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
